plugins {
    id 'com.android.application'
}

android {
    namespace 'no.probenk.widget'
    compileSdk 35

    defaultConfig {
        applicationId 'no.probenk.widget'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
